/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    JOBDIVA_USERNAME_USA: process.env.JOBDIVA_USERNAME_USA,
    JOBDIVA_PASSWORD_USA: process.env.JOBDIVA_PASSWORD_USA,
    JOBDIVA_CLIENT_ID_USA: process.env.JOBDIVA_CLIENT_ID_USA,
    JOBDIVA_USERNAME_INDIA: process.env.JOBDIVA_USERNAME_INDIA,
    JOBDIVA_PASSWORD_INDIA: process.env.JOBDIVA_PASSWORD_INDIA,
    JOBDIVA_CLIENT_ID_INDIA: process.env.JOBDIVA_CLIENT_ID_INDIA,
    NEXT_PUBLIC_CLIENT_ID: process.env.NEXT_PUBLIC_CLIENT_ID,
    NEXT_PUBLIC_TENANT_ID: process.env.NEXT_PUBLIC_TENANT_ID,
    NEXT_PUBLIC_SITE_ID: process.env.NEXT_PUBLIC_SITE_ID,
    NEXT_PUBLIC_DRIVE_ID: process.env.NEXT_PUBLIC_DRIVE_ID,
    NEXT_PUBLIC_SHAREPOINT_FOLDER: process.env.NEXT_PUBLIC_SHAREPOINT_FOLDER,
    CLIENT_SECRET: process.env.CLIENT_SECRET,
  },
}

module.exports = nextConfig 